name: "Bug Report"
description: "Report a bug"
title: "[Bug] "
labels:
  - bug
body:
  - type: textarea
    attributes:
      label: "Describe the bug"
      description: |
        A clear and concise description of what the bug is.
        If you have a screenshot of the bug, please attach it below.
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Steps to reproduce the bug"
      description: "Tell us exactly how to reproduce the bug you are experiencing."
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true