blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/TheMeinerLP/BlueMapS3Storage/discussions
    about: If you have any questions or concerns (if you dont want to use Discord), please post them in our GitHub Discussions.
