services:
  minio:
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: BLUEMAP
      MINIO_ROOT_PASSWORD: BLUEMAP
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"